"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, CircleDollarSign, CreditCard, Download, FileText, Wallet } from "lucide-react";
import { PageHeader } from "@/components/dashboard/page-header";
import { StatCard } from "@/components/dashboard/stat-card";
import { StatusBadge } from "@/components/dashboard/status-badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { getPayments } from "@/lib/dashboard-api";
import type { Payment } from "@/data/dashboard";
import { daysUntil, formatCurrency, formatDate } from "@/lib/time";
import { cn } from "@/lib/utils";

function downloadInvoice(payment: Payment) {
  const content = [
    "PIKZELKRAFT",
    "Digital Marketing & IT Solutions",
    "",
    "TAX INVOICE",
    "",
    `Invoice No: ${payment.invoiceNo}`,
    `Date: ${payment.date}`,
    "",
    "Bill To: Client",
    "",
    `Description: ${payment.description}`,
    `Amount: ${formatCurrency(payment.amount)}`,
    `Status: ${payment.status.toUpperCase()}`,
    "",
    "This is a sample invoice generated by the Pikzelkraft client dashboard.",
  ].join("\n");
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${payment.invoiceNo}.txt`;
  anchor.click();
  URL.revokeObjectURL(url);
}

export default function PaymentsPage() {
  const [payments, setPayments] = useState<Payment[]>([]);
  const [toast, setToast] = useState("");

  useEffect(() => {
    let active = true;
    void getPayments().then((data) => {
      if (active) setPayments(data);
    });
    return () => {
      active = false;
    };
  }, []);

  useEffect(() => {
    if (!toast) return;
    const timer = window.setTimeout(() => setToast(""), 3200);
    return () => window.clearTimeout(timer);
  }, [toast]);

  const totalPaid = payments.filter((p) => p.status === "paid").reduce((sum, p) => sum + p.amount, 0);
  const outstanding = payments
    .filter((p) => p.status === "pending" || p.status === "overdue")
    .reduce((sum, p) => sum + p.amount, 0);
  const nextDue = payments
    .filter((p) => p.status === "pending" || p.status === "overdue")
    .sort((a, b) => (a.dueDate ?? "9999").localeCompare(b.dueDate ?? "9999"))[0];

  function payNow(id: string) {
    setPayments((current) =>
      current.map((p) => (p.id === id ? { ...p, status: "paid" } : p))
    );
    setToast("Payment recorded — thank you!");
  }

  return (
    <div className="space-y-8">
      <PageHeader
        title="Payments"
        subtitle="Review your invoice history, outstanding amounts and upcoming dues."
      />

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 lg:gap-6">
        {payments.length > 0 ? (
          <>
            <StatCard
              icon={CircleDollarSign}
              label="Total Paid"
              value={formatCurrency(totalPaid)}
              tone="success"
              hint={`${payments.filter((p) => p.status === "paid").length} settled invoices`}
            />
            <StatCard
              icon={Wallet}
              label="Outstanding"
              value={formatCurrency(outstanding)}
              tone="warning"
              hint={`${payments.filter((p) => p.status !== "paid").length} invoices pending`}
            />
            <StatCard
              icon={CreditCard}
              label="Next Due"
              value={nextDue ? formatCurrency(nextDue.amount) : "—"}
              tone="primary"
              hint={
                nextDue
                  ? `${nextDue.invoiceNo} · ${nextDue.dueDate ? daysUntil(nextDue.dueDate) : "due"} day${nextDue.dueDate && daysUntil(nextDue.dueDate) === 1 ? "" : "s"} left`
                  : "Nothing due"
              }
            />
          </>
        ) : (
          <>
            <Skeleton className="h-32" />
            <Skeleton className="h-32" />
            <Skeleton className="h-32" />
          </>
        )}
      </div>

      <Card className="overflow-hidden p-0">
        <div className="overflow-x-auto">
          <table className="w-full min-w-[720px] text-left">
            <thead>
              <tr className="border-b border-border text-label font-semibold uppercase tracking-[0.08em] text-ink-muted">
                <th className="px-6 py-4">Invoice No</th>
                <th className="px-6 py-4">Description</th>
                <th className="px-6 py-4">Date</th>
                <th className="px-6 py-4 text-right">Amount</th>
                <th className="px-6 py-4">Status</th>
                <th className="px-6 py-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {payments.map((payment) => {
                const unsettled = payment.status !== "paid";
                return (
                  <tr
                    key={payment.id}
                    className={cn(
                      "transition-colors",
                      payment.status === "overdue" && "bg-error-soft/40",
                      payment.status === "pending" && "bg-warning-soft/40"
                    )}
                  >
                    <td className="px-6 py-4">
                      <span className="text-button font-semibold tabular text-ink">{payment.invoiceNo}</span>
                    </td>
                    <td className="max-w-[260px] px-6 py-4">
                      <p className="truncate text-body-sm text-ink">{payment.description}</p>
                      {payment.dueDate ? (
                        <p className="mt-0.5 text-caption text-ink-faint">Due {formatDate(payment.dueDate)}</p>
                      ) : null}
                    </td>
                    <td className="whitespace-nowrap px-6 py-4 text-body-sm text-ink-muted">
                      {formatDate(payment.date)}
                    </td>
                    <td className="whitespace-nowrap px-6 py-4 text-right text-button font-semibold tabular text-ink">
                      {formatCurrency(payment.amount)}
                    </td>
                    <td className="px-6 py-4">
                      <StatusBadge status={payment.status} />
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex items-center justify-end gap-2">
                        {unsettled ? (
                          <Button variant="gradient" size="sm" onClick={() => payNow(payment.id)}>
                            Pay Now
                          </Button>
                        ) : (
                          <span className="inline-flex items-center gap-1.5 text-caption font-medium text-success-text">
                            <CheckCircle2 size={15} aria-hidden />
                            Settled
                          </span>
                        )}
                        <Button
                          variant="secondary"
                          size="sm"
                          aria-label={`Download invoice ${payment.invoiceNo}`}
                          onClick={() => downloadInvoice(payment)}
                        >
                          <Download size={15} aria-hidden />
                        </Button>
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
        {payments.length === 0 ? (
          <div className="flex h-40 items-center justify-center gap-3 text-body-sm text-ink-muted">
            <FileText size={18} aria-hidden />
            Loading payment history…
          </div>
        ) : null}
      </Card>

      {toast ? (
        <div className="fixed bottom-6 right-6 z-50 flex items-center gap-2.5 rounded-md border border-success-border bg-surface px-4 py-3 shadow-md">
          <CheckCircle2 size={18} className="text-success-text" aria-hidden />
          <span className="text-button font-medium text-ink">{toast}</span>
        </div>
      ) : null}
    </div>
  );
}
