import type { AdminPayment } from "@/data/admin";
import { getClientCompany, getClientName } from "@/data/admin";
import { formatCurrency, formatDate } from "@/lib/time";
import { downloadTextFile } from "@/lib/csv";

export function downloadInvoice(payment: AdminPayment): void {
  const client = getClientName(payment.clientId);
  const company = getClientCompany(payment.clientId);
  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${payment.invoiceNo}</title>
<style>
  body { font-family: -apple-system, "Segoe UI", Roboto, sans-serif; color: #1a1f2e; margin: 40px auto; max-width: 720px; padding: 0 24px; }
  .muted { color: #6e7a8e; }
  table { width: 100%; border-collapse: collapse; margin-top: 28px; }
  th, td { text-align: left; padding: 10px 12px; border-bottom: 1px solid #e2e7ef; font-size: 14px; }
  th { background: #f6f8fc; }
  .total { font-size: 16px; font-weight: 700; text-align: right; margin-top: 20px; }
  .header { display: flex; justify-content: space-between; align-items: center; }
  .brand { font-size: 22px; font-weight: 800; }
  .box { border: 1px solid #e2e7ef; border-radius: 12px; padding: 16px 20px; margin-top: 24px; }
</style>
</head>
<body>
  <div class="header">
    <div class="brand">Pikzelkraft</div>
    <div>
      <div style="font-size:18px; font-weight:600;">${payment.invoiceNo}</div>
      <div class="muted" style="font-size:13px;">${formatDate(payment.date)}</div>
    </div>
  </div>

  <div class="box" style="margin-top: 28px;">
    <div style="font-weight:600;">Billed to</div>
    <div style="margin-top:4px;">${client} — ${company}</div>
    <div class="muted" style="font-size:13px;">Customer ID: ${payment.clientId}</div>
  </div>

  <table>
    <thead>
      <tr><th>Description</th><th>Date</th><th style="text-align:right;">Amount</th></tr>
    </thead>
    <tbody>
      <tr>
        <td>${payment.description}</td>
        <td>${formatDate(payment.date)}</td>
        <td style="text-align:right;">${formatCurrency(payment.amount)}</td>
      </tr>
    </tbody>
  </table>

  <div class="total">Total due: ${formatCurrency(payment.amount)}</div>
  <p class="muted" style="font-size:12px; margin-top:32px;">
    Status: ${payment.status.toUpperCase()} · Method: ${payment.method} · Generated by the Pikzelkraft admin dashboard.
  </p>
</body>
</html>`;

  downloadTextFile(`${payment.invoiceNo}.html`, html, "text/html");
}
